// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpmkrchfjbftgnbmvahc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbWtyY2hmamJmdGduYm12YWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODU4NzQsImV4cCI6MjA3Nzc2MTg3NH0.NnH-OlyLq-Xe6BqtHKeHWXtHADhKks1bgpwHGAjLWHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});